### ISSUE TITLE
`user` and `group` are not honoured

### ISSUE THREAD

**Issue by giorgian** [poise/application_git#2]
`application_git` ignores both `application`'s and `git`'s `user` and `group` attributes.

The former is just ignored; the latter is not taken into account in creating deploy_key and ssh_wrapper, as non-root users are not allowed to read or execute root's files.

**Comment by mbasset** [comment]
:+1: Also getting this issue which prevents checkout of repo.

**Comment by coderanger** [comment]
Workaround for now is just set it manually:

``` ruby
application '/asdf' do
  owner 'myuser'
  git 'https://github/etc' do
    onwer parent.owner
  end
end
```

Will get this in the next release of the cookbook to be handled automatically.

**Comment by mbasset** [comment]
I tried your fix. It does not work with `owner` unfortunately:

`undefined method `owner' for PoiseApplicationGit::Resource`

It seems to work if I use user though:

```
git do
    user parent.owner
    group 'www-data'
    repository app['app_source']['url']
end
```

I should also mention I am using chef 12.6

**Comment by coderanger** [comment]
Fixed via https://github.com/poise/application_git/commit/8c481a0309d47d5a4365317d90f7580c30508947

**Comment by michaelm-spindance** [comment]
I'm excited to see this fixed. Can you provide an ETA on when we can expect a new version containing this fix on the Supermarket?
