### ISSUE TITLE
Silently fails if directory exists

### ISSUE THREAD

**Issue by parhamfh** [poise/application_git#8]
I had problems cloning the repo and the logs gives of something similar to this:
`[2017-01-17T14:45:07+00:00] INFO: Processing application_git[a/b] action sync ()` 

When I enable debug log level I also see this:
`[2017-01-17T14:45:08+00:00] DEBUG: application_git[git@github.com:a/b] checkout destination /path/to/dest already exists or is a non-empty directory`

Of course the recipe breaks later on but it would be useful if the above step also passed on the cloning error in the logs, would ease troubleshooting.

**Comment by coderanger** [comment]
That is coming from the core git resource: https://github.com/chef/chef/blob/master/lib/chef/provider/git.rb#L85

Not related to this cookbook.
